### ISSUE TITLE
Is full face images in dataset can be obtained？

### ISSUE THREAD

**Issue by AgentKu** [dongzelian/multi-view-gaze#4]
Hello, I have been very interested in your work after reading your article, and I agree that multi-view training is an important way to compensate for the missing spatial relationships of a single image. 
And I think multi-view training could be applied to a larger application range, such as directly input a face image as or an image of a person in a huge scene. So, I would like to consult **if full face images of this dataset are available?**

**Comment by dongzelian** [comment]
@AgentKu Sorry, it is not available for full-face images.

**Comment by AgentKu** [comment]
OK, I see, thanks for your reply.
